import { useEffect, useState } from 'react'
import { Bell, CheckCircle2, LogOut, Save, ShieldCheck, UserRound } from 'lucide-react'
import { useReachWellContext } from '../../lib/reachwellContext'
import { supabase } from '../../lib/supabaseClient'

export function SettingsWorkspace() {
  const { organizationId, organizationName, organizationRole, user } = useReachWellContext()
  const [emailNotifications, setEmailNotifications] = useState(true)
  const [inAppNotifications, setInAppNotifications] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { if (!user) return; void (async () => { const { data } = await supabase.from('notification_preferences').select('email_enabled,in_app_enabled').eq('user_id', user.id).maybeSingle(); if (data) { setEmailNotifications(data.email_enabled !== false); setInAppNotifications(data.in_app_enabled !== false) } })() }, [user])
  const savePreferences = async () => { if (!user) return; setSaving(true); setSaved(false); setError(''); const { error: saveError } = await supabase.from('notification_preferences').upsert({ user_id: user.id, email_enabled: emailNotifications, in_app_enabled: inAppNotifications }, { onConflict: 'user_id' }); if (saveError) setError(saveError.message); else setSaved(true); setSaving(false) }
  const displayName = user?.user_metadata?.full_name || user?.user_metadata?.name || user?.email?.split('@')[0] || 'ReachWell member'
  return <div className="ops-hub rw-settings"><header className="ops-heading"><div><span className="rw-eyebrow">REACHWELL SETTINGS</span><h1>Settings</h1><p>Keep your account and workspace preferences simple and in one place.</p></div></header>{error && <div className="rw-context-alert" role="alert">{error}</div>}{saved && <div className="rw-context-alert" role="status"><CheckCircle2 size={16}/> Preferences saved.</div>}<div className="rw-settings-stack"><section className="rw-card rw-settings-section"><div className="rw-settings-icon"><UserRound size={20}/></div><div className="rw-settings-copy"><span className="rw-eyebrow">ACCOUNT</span><h2>{displayName}</h2><p>{user?.email || 'No personal email available'}</p></div><div className="rw-settings-detail"><span>Signed in as</span><strong>{organizationRole || 'Member'}</strong></div></section><section className="rw-card rw-settings-section"><div className="rw-settings-icon"><ShieldCheck size={20}/></div><div className="rw-settings-copy"><span className="rw-eyebrow">WORKSPACE</span><h2>{organizationName || 'Organization workspace'}</h2><p>Your organization access is controlled by membership and database policies.</p></div><div className="rw-settings-detail"><span>Your role</span><strong>{organizationRole || 'Member'}</strong></div></section><section className="rw-card rw-settings-section rw-settings-preferences"><div className="rw-settings-icon"><Bell size={20}/></div><div className="rw-settings-copy"><span className="rw-eyebrow">NOTIFICATIONS</span><h2>How ReachWell keeps you informed</h2><p>Choose the notification channels you want to use.</p></div><div className="rw-settings-options"><label><span><strong>In-app notifications</strong><small>Activity and operational alerts inside ReachWell.</small></span><input type="checkbox" checked={inAppNotifications} onChange={e => setInAppNotifications(e.target.checked)}/></label><label><span><strong>Email notifications</strong><small>Notification emails when your organization has delivery configured.</small></span><input type="checkbox" checked={emailNotifications} onChange={e => setEmailNotifications(e.target.checked)}/></label><button className="rw-primary-button" onClick={() => void savePreferences()} disabled={saving || !organizationId}><Save size={16}/> {saving ? 'Saving…' : 'Save preferences'}</button></div></section><section className="rw-card rw-settings-section rw-settings-account-action"><div className="rw-settings-copy"><span className="rw-eyebrow">SESSION</span><h2>Sign out</h2><p>End this ReachWell session on this device.</p></div><button className="rw-secondary-button" onClick={() => void supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></section></div></div>
}
