alter policy "budget_lines_finance_manage" on public.budget_lines to authenticated;
alter policy "budget_lines_finance_select" on public.budget_lines to authenticated;
alter policy "budgets_finance_manage" on public.budgets to authenticated;
alter policy "budgets_finance_select" on public.budgets to authenticated;
alter policy "campaigns_finance_manage" on public.campaigns to authenticated;
alter policy "campaigns_finance_select" on public.campaigns to authenticated;
alter policy "donor_statements_insert" on public.donor_annual_statements to authenticated;
alter policy "donor_statements_select" on public.donor_annual_statements to authenticated;
alter policy "donor_statements_update" on public.donor_annual_statements to authenticated;
alter policy "donors_finance_insert" on public.donors to authenticated;
alter policy "donors_finance_select" on public.donors to authenticated;
alter policy "donors_finance_update" on public.donors to authenticated;
alter policy "funds_finance_manage" on public.funds to authenticated;
alter policy "funds_finance_select" on public.funds to authenticated;
alter policy "merch_finance_manage" on public.merch_products to authenticated;
alter policy "merch_finance_select" on public.merch_products to authenticated;
alter policy "owners admins can request and view exports" on public.organization_exports to authenticated;
alter policy "owners admins can request exports" on public.organization_exports to authenticated;
alter policy "owners admins can update export requests" on public.organization_exports to authenticated;
alter policy "authorized members can upload files" on public.organization_files to authenticated;
alter policy "org members can view active and deleted files" on public.organization_files to authenticated;
alter policy "owners admins can manage file records" on public.organization_files to authenticated;
alter policy "org members can view subscription lifecycle" on public.organization_subscriptions to authenticated;
alter policy "owners admins manage subscription lifecycle" on public.organization_subscriptions to authenticated;
alter policy "sales_line_items_insert" on public.sales_line_items to authenticated;
alter policy "sales_line_items_select" on public.sales_line_items to authenticated;
alter policy "sales_line_items_update" on public.sales_line_items to authenticated;
alter policy "sales_finance_insert" on public.sales_transactions to authenticated;
alter policy "sales_finance_select" on public.sales_transactions to authenticated;
alter policy "sales_finance_update" on public.sales_transactions to authenticated;
