DROP POLICY IF EXISTS assignment_assignees_manage ON public.assignment_assignees;
DROP POLICY IF EXISTS assignment_objectives_manage ON public.assignment_objectives;
DROP POLICY IF EXISTS event_participants_manage_scoped ON public.event_participants;
DROP POLICY IF EXISTS event_teams_manage_scoped ON public.event_teams;
DROP POLICY IF EXISTS events_manage_staff ON public.events;
DROP POLICY IF EXISTS followups_manage_authorized ON public.follow_ups;
DROP POLICY IF EXISTS needs_manage_authorized ON public.needs;
DROP POLICY IF EXISTS people_team_memberships_manage_team ON public.people_team_memberships;
DROP POLICY IF EXISTS team_members_manage_scoped ON public.team_members;
DROP POLICY IF EXISTS prayer_manage_authorized ON public.prayer_requests;
DROP POLICY IF EXISTS people_manage_staff ON public.people;
DROP POLICY IF EXISTS households_manage_staff ON public.households;
DROP POLICY IF EXISTS teams_manage_leadership ON public.teams;
DROP POLICY IF EXISTS organizations_manage_admin ON public.organizations;
DROP POLICY IF EXISTS org_members_owner_manage ON public.organization_members;
DROP POLICY IF EXISTS finance_access_manage ON public.organization_finance_access;
DROP POLICY IF EXISTS accounts_finance_manage ON public.finance_accounts;
DROP POLICY IF EXISTS categories_finance_manage ON public.financial_categories;
DROP POLICY IF EXISTS funds_finance_manage ON public.funds;
DROP POLICY IF EXISTS budgets_finance_manage ON public.budgets;
DROP POLICY IF EXISTS budget_lines_finance_manage ON public.budget_lines;
DROP POLICY IF EXISTS campaigns_finance_manage ON public.campaigns;
DROP POLICY IF EXISTS merch_finance_manage ON public.merch_products;
DROP POLICY IF EXISTS transactions_finance_update ON public.financial_transactions;
DROP POLICY IF EXISTS giving_finance_update ON public.giving_transactions;
DROP POLICY IF EXISTS giving_receipts_update ON public.giving_receipts;
DROP POLICY IF EXISTS donor_statements_update ON public.donor_annual_statements;
DROP POLICY IF EXISTS households_member_read ON public.households;
DROP POLICY IF EXISTS people_member_read ON public.people;
DROP POLICY IF EXISTS events_member_read ON public.events;
DROP POLICY IF EXISTS event_participants_read_event ON public.event_participants;
DROP POLICY IF EXISTS event_teams_member_read ON public.event_teams;
DROP POLICY IF EXISTS team_members_select_team_or_org ON public.team_members;
DROP POLICY IF EXISTS teams_select_org_member ON public.teams;
DROP POLICY IF EXISTS people_team_memberships_member_read ON public.people_team_memberships;
DROP POLICY IF EXISTS followups_read_org ON public.follow_ups;
DROP POLICY IF EXISTS needs_read_org ON public.needs;
DROP POLICY IF EXISTS prayer_read_authorized ON public.prayer_requests;
DROP POLICY IF EXISTS assignment_assignees_read ON public.assignment_assignees;
DROP POLICY IF EXISTS assignment_objectives_read ON public.assignment_objectives;
DROP POLICY IF EXISTS budget_lines_finance_select ON public.budget_lines;
DROP POLICY IF EXISTS budgets_finance_select ON public.budgets;
DROP POLICY IF EXISTS campaigns_finance_select ON public.campaigns;
DROP POLICY IF EXISTS finance_accounts_finance_select ON public.finance_accounts;
DROP POLICY IF EXISTS financial_categories_finance_select ON public.financial_categories;
DROP POLICY IF EXISTS funds_finance_select ON public.funds;
DROP POLICY IF EXISTS merch_finance_select ON public.merch_products;
DROP POLICY IF EXISTS organization_members_select_same_org ON public.organization_members;
DROP POLICY IF EXISTS organization_members_select_own ON public.organization_members;
DROP POLICY IF EXISTS organization_subscriptions_select ON public.organization_subscriptions;
DROP POLICY IF EXISTS organizations_select_member ON public.organizations;
DROP POLICY IF EXISTS organization_finance_access_select ON public.organization_finance_access;
DROP POLICY IF EXISTS prayer_read_authorized ON public.prayer_requests;

CREATE POLICY assignment_assignees_access ON public.assignment_assignees FOR ALL TO authenticated USING (can_manage_assignment(assignment_id) OR user_id = (SELECT auth.uid())) WITH CHECK (can_manage_assignment(assignment_id) OR user_id = (SELECT auth.uid()));
CREATE POLICY assignment_objectives_access ON public.assignment_objectives FOR ALL TO authenticated USING (can_manage_assignment(assignment_id)) WITH CHECK (can_manage_assignment(assignment_id));
CREATE POLICY event_participants_access ON public.event_participants FOR ALL TO authenticated USING (can_manage_event(event_id) OR EXISTS (SELECT 1 FROM events e WHERE e.id=event_id AND is_org_member(e.organization_id))) WITH CHECK (can_manage_event(event_id));
CREATE POLICY event_teams_access ON public.event_teams FOR ALL TO authenticated USING (can_manage_event(event_id) OR EXISTS (SELECT 1 FROM events e WHERE e.id=event_id AND is_org_member(e.organization_id))) WITH CHECK (can_manage_event(event_id));
CREATE POLICY events_access ON public.events FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin','director','coordinator']));
CREATE POLICY followups_access ON public.follow_ups FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (is_org_member(organization_id));
CREATE POLICY needs_access ON public.needs FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (is_org_member(organization_id));
CREATE POLICY prayer_access ON public.prayer_requests FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (is_org_member(organization_id));
CREATE POLICY people_access ON public.people FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin','director','coordinator']));
CREATE POLICY households_access ON public.households FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin','director','coordinator']));
CREATE POLICY teams_access ON public.teams FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin','director','coordinator']));
CREATE POLICY people_team_memberships_access ON public.people_team_memberships FOR ALL TO authenticated USING (is_org_member(organization_id)) WITH CHECK (is_org_member(organization_id) AND EXISTS (SELECT 1 FROM people p WHERE p.id=person_id AND p.organization_id=people_team_memberships.organization_id) AND EXISTS (SELECT 1 FROM teams t WHERE t.id=team_id AND t.organization_id=people_team_memberships.organization_id));
CREATE POLICY team_members_access ON public.team_members FOR ALL TO authenticated USING (can_manage_team(team_id) OR EXISTS (SELECT 1 FROM teams t WHERE t.id=team_id AND is_org_member(t.organization_id))) WITH CHECK (can_manage_team(team_id));
CREATE POLICY organizations_access ON public.organizations FOR ALL TO authenticated USING (is_org_member(id)) WITH CHECK (has_org_role(id, ARRAY['owner','admin','director','coordinator']));
CREATE POLICY org_members_select ON public.organization_members FOR SELECT TO authenticated USING (organization_id IN (SELECT om.organization_id FROM public.organization_members om WHERE om.user_id=(SELECT auth.uid()) AND om.status='active'));
CREATE POLICY org_members_insert ON public.organization_members FOR INSERT TO authenticated WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin']));
CREATE POLICY org_members_update ON public.organization_members FOR UPDATE TO authenticated USING (has_org_role(organization_id, ARRAY['owner','admin'])) WITH CHECK (has_org_role(organization_id, ARRAY['owner','admin']));
CREATE POLICY org_members_delete ON public.organization_members FOR DELETE TO authenticated USING (has_org_role(organization_id, ARRAY['owner','admin']));
